
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
     build:

       runs-on: ubuntu-latest

       services:
         mysql:
           image: mysql:8.0
           env:
             MYSQL_DATABASE: sporthubportal
             MYSQL_USER: root
             MYSQL_PASSWORD: 1234
             MYSQL_ROOT_PASSWORD: 1234
           ports:
             - 3306
           options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

       steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 1.8
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: '17'

         - name: Give github permission to use gradle
           run: chmod +x ./gradlew

         - name: Build
           run: ./gradlew build
            
