
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

     build:

       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 1.8
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: '17'

         connect:
           stage: connect
           image: mysql
           before_script:
             - mysql --version
             - apt-get update -q && apt-get install -qqy --no-install-recommends mysql-client
           script:
             - echo "create database sporthubportal;" | mysql --user=root --password="1234" --host=mysql
             - mysql --user=root --password="1234" --host=mysql -e "show databases; use $MYSQL_DATABASE_NAME; show tables;"

         - name: Give github permission to use gradle
           run: chmod +x ./gradlew

         - name: Build
           run: ./gradlew build
            
