
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
     build:

       runs-on: ubuntu-latest

       services:
         mysql:
           image: mysql:8.0
           env:
             MYSQL_ROOT_PASSWORD: 1234
           ports:
             - 3306
           options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

       steps:

         - name: Verify MySQL connection from host
           run: sudo apt-get install mysql-server

         - name: Start mySql
           run: systemctl start mysql

         - name: MySQL status
           run: systemctl status mysqld.service

             #         - uses: actions/checkout@v3
#
#         - name: Set up JDK 1.8
#           uses: actions/setup-java@v3
#           with:
#             distribution: 'temurin'
#             java-version: '17'
#
#         - name: Give github permission to use gradle
#           run: chmod +x ./gradlew
#
#         - name: Build
#           run: ./gradlew build
            
