
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
     build:

       runs-on: ubuntu-latest

       services:
         mysql:
           image: mysql:latest
           env:
             MYSQL_ROOT_PASSWORD: 1234
             MYSQL_DATABASE: sporthubportal
             MYSQL_HOST: mysql

       steps:
         - name: stop mysql
           run:
             systemctl stop mysql

         - name: run mysql
           run:
             systemctl start mysql

         - name: use db
           run:
             mysql --user=root --password="1234" "sporthubportal"



             #         - uses: actions/checkout@v3
#
#         - name: Set up JDK 1.8
#           uses: actions/setup-java@v3
#           with:
#             distribution: 'temurin'
#             java-version: '17'
#
#         - name: Give github permission to use gradle
#           run: chmod +x ./gradlew
#
#         - name: Build
#           run: ./gradlew build
            
