

name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Give github permission to use gradle
        run: chmod +x ./gradlew

      - name: Build
        run: ./gradlew build

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Set up MySQL
        run:
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE sporthubportal;' -u root -p 1234

      - name: Give github permission to use gradle
        run: chmod +x ./gradlew

      - name: Run tests
        run: ./gradlew test

      - name: Update documentstion
        run: ./gradlew asciidoctor


            
