
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
     build:

       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v3
         - uses: actions/setup-java@v3
           with:
             java-version: '17'
             distribution: 'adopt'

         - name: Shutdown Ubuntu MySQL (SUDO)
           run: sudo service mysql stop

         - uses: mirromutth/mysql-action@v1.1
           with:
             mysql version: '8.0'
             mysql database: 'sporthubportal'
             mysql root password: '1234'
             mysql user: 'root'
             mysql password: '1234'
         - name: Give github permission to use gradle
           run: chmod +x ./gradlew

         - name: Build
           run: ./gradlew build