
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
     build:

       runs-on: ubuntu-latest

       steps:
         - uses: actions/checkout@v3

         - name: Set up JDK 1.8
           uses: actions/setup-java@v3
           with:
             distribution: 'temurin'
             java-version: '17'

         - uses: jordiprats/mysql-action@v1.1
           with:
             mysql version: '8.0'

         - name: Give github permission to use gradle
           run: chmod +x ./gradlew

         - name: Build
           run: ./gradlew build
            
